version: '3.8'

services:
  web:
    image: ${WEB_IMAGE:-ghcr.io/van-sprundel/partijgedrag-web:latest}
    ports:
      - "3000:3000"  # Nginx will proxy to this port
    deploy:
      replicas: 2  # Run 2 instances for redundancy
      update_config:
        parallelism: 1        # Update 1 at a time
        delay: 10s            # Wait 10s between updates
        failure_action: rollback
        order: start-first    # Start new before stopping old (ZERO DOWNTIME!)
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3000
      CORS_ORIGIN: ${CORS_ORIGIN:-https://your-domain.nl}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - partijgedrag

  etl:
    image: ${ETL_IMAGE:-ghcr.io/van-sprundel/partijgedrag-etl:latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - partijgedrag

volumes:
  postgres_data:

networks:
  partijgedrag:
    driver: overlay
