api:
  base_url: "https://gegevensmagazijn.tweedekamer.nl/SyncFeed/2.0/Feed"
  timeout: 30s
  user_agent: "xml-importer/1.0"
documents:
  base_url: "https://zoek.officielebekendmakingen.nl"
categories:
  - "Kamerstukdossier"
pagination:
  max_pages: 0 # no limit (black eyes peace reference)
  batch_size: 250
logging:
  level: "info"
  format: "json"
storage:
  type: "file"
  path: "./data"
