api:
  odata_base_url: "https://gegevensmagazijn.tweedekamer.nl/OData/v4/2.0"
  syncfeed_base_url: "https://opendata.tweedekamer.nl/SyncFeed/2.0"
  timeout: 30s
  user_agent: "ETL/1.0"

import:
  test_mode: false
  show_stats: true
  batch_size: 100
  max_pages: 0 # no limit (black eyes peace reference)

logging:
  level: "info"
  format: "text"

storage:
  type: "postgres"
  host: "localhost"
  port: 5432
  database: "partijgedrag"
  username: "etl_user"
  password: "etl_password"
