export const ACCESS_TOKEN_EXPIRES_IN_MINUTES = 20160;
export const ACCESS_TOKEN_EXPIRES_IN = `${ACCESS_TOKEN_EXPIRES_IN_MINUTES}m`;
export const REFRESH_TOKEN_EXPIRES_IN_MINUTES = 20160;
export const REFRESH_TOKEN_EXPIRES_IN = `${REFRESH_TOKEN_EXPIRES_IN_MINUTES}m`;
