services:
  postgres:
    image: postgres:15
    container_name: partijgedrag-db
    environment:
      POSTGRES_DB: partijgedrag
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d partijgedrag"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
